version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: kaoba_db
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./Backend/x
    container_name: kaoba-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8081:8081'
    dns:
      - 8.8.8.8
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/kaoba_db?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    networks:
      - app-network

  admin-frontend:
    build: ./Frontnd/admin
    container_name: kaoba-admin-frontend
    restart: always
    ports:
      - '4200:80'
    depends_on:
      - backend
    networks:
      - app-network

  client:
    build: ./Frontnd/Client
    container_name: kaoba-client
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:
